specs = [{'codings': ['C44'],
  'name': 'C44 Other malignant neoplasms of skin',
  'source': 'ICD-10'},
 {'codings': ['C50'],
  'name': 'C50 Malignant neoplasm of breast',
  'sex_filter': 'F',
  'source': 'ICD-10'},
 {'codings': ['D12'],
  'name': 'D12 Benign neoplasm of colon, rectum, anus and anal canal',
  'source': 'ICD-10'},
 {'codings': ['D64'], 'name': 'D64 Other anaemias', 'source': 'ICD-10'},
 {'codings': ['D649'], 'name': 'D64.9 Anaemia, unspecified', 'source': 'ICD-10'},
 {'codings': ['E03'], 'name': 'E03 Other hypothyroidism', 'source': 'ICD-10'},
 {'codings': ['E039'],
  'name': 'E03.9 Hypothyroidism, unspecified',
  'source': 'ICD-10'},
 {'codings': ['E11'],
  'name': 'E11 Non-insulin-dependent diabetes mellitus',
  'source': 'ICD-10'},
 {'codings': ['E119'], 'name': 'E11.9 Without complications', 'source': 'ICD-10'},
 {'codings': ['E66'], 'name': 'E66 Obesity', 'source': 'ICD-10'},
 {'codings': ['E669'], 'name': 'E66.9 Obesity, unspecified', 'source': 'ICD-10'},
 {'codings': ['E78'],
  'name': 'E78 Disorders of lipoprotein metabolism and other lipidaemias',
  'source': 'ICD-10'},
 {'codings': ['E780'],
  'name': 'E78.0 Pure hypercholesterolaemia',
  'source': 'ICD-10'},
 {'codings': ['F17'],
  'name': 'F17 Mental and behavioural disorders due to use of tobacco',
  'source': 'ICD-10'},
 {'codings': ['F171'], 'name': 'F17.1 Harmful use', 'source': 'ICD-10'},
 {'codings': ['F32'], 'name': 'F32 Depressive episode', 'source': 'ICD-10'},
 {'codings': ['F329'],
  'name': 'F32.9 Depressive episode, unspecified',
  'source': 'ICD-10'},
 {'codings': ['H26'], 'name': 'H26 Other cataract', 'source': 'ICD-10'},
 {'codings': ['H269'], 'name': 'H26.9 Cataract, unspecified', 'source': 'ICD-10'},
 {'codings': ['I10'],
  'name': 'I10 Essential (primary) hypertension',
  'source': 'ICD-10'},
 {'codings': ['I20'], 'name': 'I20 Angina pectoris', 'source': 'ICD-10'},
 {'codings': ['I209'],
  'name': 'I20.9 Angina pectoris, unspecified',
  'source': 'ICD-10'},
 {'codings': ['I25'],
  'name': 'I25 Chronic ischaemic heart disease',
  'source': 'ICD-10'},
 {'codings': ['I251'],
  'name': 'I25.1 Atherosclerotic heart disease',
  'source': 'ICD-10'},
 {'codings': ['I259'],
  'name': 'I25.9 Chronic ischaemic heart disease, unspecified',
  'source': 'ICD-10'},
 {'codings': ['I48'],
  'name': 'I48 Atrial fibrillation and flutter',
  'source': 'ICD-10'},
 {'codings': ['I84'], 'name': 'I84 Haemorrhoids', 'source': 'ICD-10'},
 {'codings': ['I849'],
  'name': 'I84.9 Unspecified haemorrhoids without complication',
  'source': 'ICD-10'},
 {'codings': ['J18'],
  'name': 'J18 Pneumonia, organism unspecified',
  'source': 'ICD-10'},
 {'codings': ['J45'], 'name': 'J45 Asthma', 'source': 'ICD-10'},
 {'codings': ['J459'], 'name': 'J45.9 Asthma, unspecified', 'source': 'ICD-10'},
 {'codings': ['K21'],
  'name': 'K21 Gastro-oesophageal reflux disease',
  'source': 'ICD-10'},
 {'codings': ['K219'],
  'name': 'K21.9 Gastro-oesophageal reflux disease without oesophagitis',
  'source': 'ICD-10'},
 {'codings': ['K29'], 'name': 'K29 Gastritis and duodenitis', 'source': 'ICD-10'},
 {'codings': ['K297'],
  'name': 'K29.7 Gastritis, unspecified',
  'source': 'ICD-10'},
 {'codings': ['K30'], 'name': 'K30 Dyspepsia', 'source': 'ICD-10'},
 {'codings': ['K40'], 'name': 'K40 Inguinal hernia', 'source': 'ICD-10'},
 {'codings': ['K409'],
  'name': 'K40.9 Unilateral or unspecified inguinal hernia, without '
          'obstruction or gangrene',
  'source': 'ICD-10'},
 {'codings': ['K44'], 'name': 'K44 Diaphragmatic hernia', 'source': 'ICD-10'},
 {'codings': ['K449'],
  'name': 'K44.9 Diaphragmatic hernia without obstruction or gangrene',
  'source': 'ICD-10'},
 {'codings': ['K52'],
  'name': 'K52 Other non-infective gastro-enteritis and colitis',
  'source': 'ICD-10'},
 {'codings': ['K529'],
  'name': 'K52.9 Non-infective gastro-enteritis and colitis, unspecified',
  'source': 'ICD-10'},
 {'codings': ['K57'],
  'name': 'K57 Diverticular disease of intestine',
  'source': 'ICD-10'},
 {'codings': ['K573'],
  'name': 'K57.3 Diverticular disease of large intestine without perforation '
          'or abscess',
  'source': 'ICD-10'},
 {'codings': ['K59'],
  'name': 'K59 Other functional intestinal disorders',
  'source': 'ICD-10'},
 {'codings': ['K590'], 'name': 'K59.0 Constipation', 'source': 'ICD-10'},
 {'codings': ['K62'],
  'name': 'K62 Other diseases of anus and rectum',
  'source': 'ICD-10'},
 {'codings': ['K625'],
  'name': 'K62.5 Haemorrhage of anus and rectum',
  'source': 'ICD-10'},
 {'codings': ['K63'],
  'name': 'K63 Other diseases of intestine',
  'source': 'ICD-10'},
 {'codings': ['K635'], 'name': 'K63.5 Polyp of colon', 'source': 'ICD-10'},
 {'codings': ['K80'], 'name': 'K80 Cholelithiasis', 'source': 'ICD-10'},
 {'codings': ['M13'], 'name': 'M13 Other arthritis', 'source': 'ICD-10'},
 {'codings': ['M139'],
  'name': 'M13.9 Arthritis, unspecified',
  'source': 'ICD-10'},
 {'codings': ['M16'],
  'name': 'M16 Coxarthrosis [arthrosis of hip]',
  'source': 'ICD-10'},
 {'codings': ['M17'],
  'name': 'M17 Gonarthrosis [arthrosis of knee]',
  'source': 'ICD-10'},
 {'codings': ['M179'],
  'name': 'M17.9 Gonarthrosis, unspecified',
  'source': 'ICD-10'},
 {'codings': ['M19'], 'name': 'M19 Other arthrosis', 'source': 'ICD-10'},
 {'codings': ['M199'],
  'name': 'M19.9 Arthrosis, unspecified',
  'source': 'ICD-10'},
 {'codings': ['M23'],
  'name': 'M23 Internal derangement of knee',
  'source': 'ICD-10'},
 {'codings': ['M25'],
  'name': 'M25 Other joint disorders, not elsewhere classified',
  'source': 'ICD-10'},
 {'codings': ['M54'], 'name': 'M54 Dorsalgia', 'source': 'ICD-10'},
 {'codings': ['M79'],
  'name': 'M79 Other soft tissue disorders, not elsewhere classified',
  'source': 'ICD-10'},
 {'codings': ['N39'],
  'name': 'N39 Other disorders of urinary system',
  'source': 'ICD-10'},
 {'codings': ['N390'],
  'name': 'N39.0 Urinary tract infection, site not specified',
  'source': 'ICD-10'},
 {'codings': ['N40'], 'name': 'N40 Hyperplasia of prostate', 'source': 'ICD-10'},
 {'codings': ['N81'], 'name': 'N81 Female genital prolapse', 'source': 'ICD-10','sex_filter': 'F',},
 
 {'codings': ['N92'],
  'name': 'N92 Excessive, frequent and irregular menstruation',
  'source': 'ICD-10'},
 {'codings': ['R07'], 'name': 'R07 Pain in throat and chest', 'source': 'ICD-10'},
 {'codings': ['R074'],
  'name': 'R07.4 Chest pain, unspecified',
  'source': 'ICD-10'},
 {'codings': ['R10'],
  'name': 'R10 Abdominal and pelvic pain',
  'source': 'ICD-10'},
 {'codings': ['R104'],
  'name': 'R10.4 Other and unspecified abdominal pain',
  'source': 'ICD-10'},
 {'codings': ['R11'], 'name': 'R11 Nausea and vomiting', 'source': 'ICD-10'},
 {'codings': ['R19'],
  'name': 'R19 Other symptoms and signs involving the digestive system and '
          'abdomen',
  'source': 'ICD-10'},
 {'codings': ['R194'], 'name': 'R19.4 Change in bowel habit', 'source': 'ICD-10'},
 {'codings': ['R31'], 'name': 'R31 Unspecified haematuria', 'source': 'ICD-10'},
 {'codings': ['R69'],
  'name': 'R69 Unknown and unspecified causes of morbidity',
  'source': 'ICD-10'},
 {'codings': ['T81'],
  'name': 'T81 Complications of procedures, not elsewhere classified',
  'source': 'ICD-10'},
 {'codings': ['Y83'],
  'name': 'Y83 Surgical operation and other surgical procedures as the cause '
          'of abnormal reaction of the patient, or of later complication, '
          'without mention of misadventure at the time of the procedure',
  'source': 'ICD-10'},
 {'codings': ['Z51'], 'name': 'Z51 Other medical care', 'source': 'ICD-10'},
 {'codings': ['Z53'],
  'name': 'Z53 Persons encountering health services for specifie procedures, '
          'not carried out',
  'source': 'ICD-10'},
 {'codings': ['Z538'],
  'name': 'Z53.8 Procedure not carried out for other reasons',
  'source': 'ICD-10'},
 {'codings': ['Z82'],
  'name': 'Z82 Family history of certain disabilities and chronic diseases '
          'leading to disablement',
  'source': 'ICD-10'},
 {'codings': ['Z824'],
  'name': 'Z82.4 Family history of ischaemic heart disease and other diseases '
          'of the circulatory system',
  'source': 'ICD-10'},
 {'codings': ['Z85'],
  'name': 'Z85 Personal history of malignant neoplasm',
  'source': 'ICD-10'},
 {'codings': ['Z86'],
  'name': 'Z86 Personal history of certain other diseases',
  'source': 'ICD-10'},
 {'codings': ['Z864'],
  'name': 'Z86.4 Personal history of psychoactive substance abuse',
  'source': 'ICD-10'},
 {'codings': ['Z867'],
  'name': 'Z86.7 Personal history of diseases of the circulatory system',
  'source': 'ICD-10'},
 {'codings': ['Z87'],
  'name': 'Z87 Personal history of other diseases and conditions',
  'source': 'ICD-10'},
 {'codings': ['Z871'],
  'name': 'Z87.1 Personal history of diseases of the digestive system',
  'source': 'ICD-10'},
 {'codings': ['Z88'],
  'name': 'Z88 Personal history of allergy to drugs, medicaments and '
          'biologocal substances',
  'source': 'ICD-10'},
 {'codings': ['Z880'],
  'name': 'Z88.0 Personal history of allergy to penicillin',
  'source': 'ICD-10'},
 {'codings': ['Z90'],
  'name': 'Z90 Acquired absence of organs, not elsewhere classified',
  'source': 'ICD-10'},
 {'codings': ['Z92'],
  'name': 'Z92 Personal history of medical treatment',
  'source': 'ICD-10'},
 {'codings': ['Z921'],
  'name': 'Z92.1 Personal history of long-term (current) use of anticoagulants',
  'source': 'ICD-10'},
 {'codings': ['Z922'],
  'name': 'Z92.2 Personal history of long-term (current) use of other '
          'medicaments',
  'source': 'ICD-10'},
 {'codings': ['Z95'],
  'name': 'Z95 Presence of cardiac and vascular implants and grafts',
  'source': 'ICD-10'},
 {'codings': ['Z96'],
  'name': 'Z96 Presence of other functional implants',
  'source': 'ICD-10'},
 {'codings': ['Z966'],
  'name': 'Z96.6 Presence of orthopaedic joint implants',
  'source': 'ICD-10'}]


